const menuCreator = () => {
  const body = document.querySelector('body');
  const section = document.createElement('section');
  const firstDiv = document.createElement('div');
  const secondDiv = document.createElement('div');
  const thirdDiv = document.createElement('div');
  const firtsH5 = document.createElement('h5');
  const secondH5 = document.createElement('h5');
  const thirdH5 = document.createElement('h5');
  const generalH2 = document.createElement('h2');
  const firstP = document.createElement('p');
  const secondP = document.createElement('p');
  const thirdP = document.createElement('p');
  const fourthP = document.createElement('p');
  const fifthP = document.createElement('p');
  const sixthP = document.createElement('p');
  const seventhP = document.createElement('p');
  const eighthP = document.createElement('p');
  const ninthP = document.createElement('p');
  const tenthP = document.createElement('p');
  const eleventhP = document.createElement('p');
  const twelfthP = document.createElement('p');
  const thirteenthP = document.createElement('p');
  const fourteenthP = document.createElement('p');
  const fifteenthP = document.createElement('p');
  const sixteenthP = document.createElement('p');
  const seventeenthP = document.createElement('p');
  const eighteenthP = document.createElement('p');
  const nineteenthP = document.createElement('p');
  const tweentiethP = document.createElement('p');
  const twentyonethP = document.createElement('p');
  const twentytwothP = document.createElement('p');
  const twentythreethP = document.createElement('p');
  const twentyfourthP = document.createElement('p');
  const twentyfifthP = document.createElement('p');
  const twentysixthP = document.createElement('p');
  const twentyseventhP = document.createElement('p');
  firtsH5.textContent = 'Garden';
  secondH5.textContent = 'Sea';
  thirdH5.textContent = 'Land';
  firstP.textContent = '—  Sautéed Swiss Chard  —';
  secondP.textContent = 'garlic, balsamic reduction';
  thirdP.textContent = '$7';
  fourthP.textContent = '—  Hen of the Woods  —';
  fifthP.textContent = 'shallots, thyme, black pepper';
  sixthP.textContent = '$8';
  seventhP.textContent = '—  Roasted Romanesco  —';
  eighthP.textContent = 'onion, sage, pecorino romano';
  ninthP.textContent = '$9';
  tenthP.textContent = '—  Grilled Octopus  —';
  eleventhP.textContent = 'bay leaf, whole peppercorns, lemon';
  twelfthP.textContent = '$20';
  thirteenthP.textContent = '—  Crab Ravioli  —';
  fourteenthP.textContent = 'garlic, white wine, basil, parsley, ricotta';
  fifteenthP.textContent = '$22';
  sixteenthP.textContent = '—  Wood-Fired Sea Bream  —';
  seventeenthP.textContent = 'artichoke, capers, rosemary, thyme';
  eighteenthP.textContent = '$25';
  nineteenthP.textContent = '—  Fried Quail  —';
  tweentiethP.textContent = 'paprika, turmeric, black pepper, ginger';
  twentyonethP.textContent = '$18';
  twentytwothP.textContent = '—  Escargot  —';
  twentythreethP.textContent = 'garlic, shallots, parsley, black pepper';
  twentyfourthP.textContent = '$19';
  twentyfifthP.textContent = '—  Lamb Stew  —';
  twentysixthP.textContent = 'roma tomatoes, cannellini beans, onion';
  twentyseventhP.textContent = '$21';
  generalH2.textContent = 'Menu';
  firstDiv.appendChild(firtsH5);
  firstDiv.appendChild(firstP);
  firstDiv.appendChild(secondP);
  firstDiv.appendChild(thirdP);
  firstDiv.appendChild(fourthP);
  firstDiv.appendChild(fifthP);
  firstDiv.appendChild(sixthP);
  firstDiv.appendChild(seventhP);
  firstDiv.appendChild(eighthP);
  firstDiv.appendChild(ninthP);
  secondDiv.appendChild(secondH5);
  secondDiv.appendChild(tenthP);
  secondDiv.appendChild(eleventhP);
  secondDiv.appendChild(twelfthP);
  secondDiv.appendChild(thirteenthP);
  secondDiv.appendChild(fourteenthP);
  secondDiv.appendChild(fifteenthP);
  secondDiv.appendChild(sixteenthP);
  secondDiv.appendChild(seventeenthP);
  secondDiv.appendChild(eighteenthP);
  thirdDiv.appendChild(thirdH5);
  thirdDiv.appendChild(nineteenthP);
  thirdDiv.appendChild(tweentiethP);
  thirdDiv.appendChild(twentyonethP);
  thirdDiv.appendChild(twentytwothP);
  thirdDiv.appendChild(twentythreethP);
  thirdDiv.appendChild(twentyfourthP);
  thirdDiv.appendChild(twentyfifthP);
  thirdDiv.appendChild(twentysixthP);
  thirdDiv.appendChild(twentyseventhP);
  section.appendChild(firstDiv);
  section.appendChild(secondDiv);
  section.appendChild(thirdDiv);
  body.appendChild(generalH2);
  section.setAttribute('class', 'modifySection d-flex justify-content-center bg-info text-center mx-auto w-75 mt-5 py-5 text-light font-weight-bold');
  firstDiv.setAttribute('class', 'mx-4');
  secondDiv.setAttribute('class', 'mx-4');
  thirdDiv.setAttribute('class', 'mx-4');
  generalH2.setAttribute('class', 'text-center text-primary mt-4 pr-5');
  body.appendChild(section);
};

export default menuCreator;